Используя обработку исключения try/catch 
print row 1
